FROM node:latest AS builder

RUN npm install -g elm
WORKDIR /app

COPY . .
RUN mkdir -p /dist
RUN elm make src/Main.elm --output=dist/main.js

FROM nginx:alpine
COPY nginx/prod.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/public /usr/share/nginx/html
COPY --from=builder /app/dist/main.js /usr/share/nginx/html/main.js

RUN chmod -R a+r /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
