services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - RUST_LOG=info
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  frontend-dist:
