services:
  backend:
    container_name: saavu-staging-backend
    image: saavu-staging
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - staging-db-data:/app/data
    networks:
      - staging-saavu-net
    expose:
      - "5000"
    restart: unless-stopped

  frontend:
    container_name: saavu-staging-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    volumes:
      - staging-frontend-dist:/app/dist

  nginx:
    container_name: saavu-staging-nginx
    image: nginx:alpine
    networks:
      - staging-saavu-net
    ports:
      - "8001:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./frontend/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - staging-frontend-dist:/usr/share/nginx/html:ro

volumes:
  staging-db-data:
  staging-frontend-dist:

networks:
  staging-saavu-net:

