name: Deploy to staging

on:
  push:
    branches:
      - staging
      - fix/vps-action

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up staging
        run: |
          rm -rf /home/saavu/staging
          mkdir -p /home/saavu/staging
          cp -r . /home/saavu/staging
          cd /home/saavu/staging

      - name: Set up Docker Buildx (optional but useful for caching/build)
        uses: docker/setup-buildx-action@v3

      - name: Build staging
        run: docker compose -f docker-compose.staging.yml build

      - name: Restore .env file
        run: cp /home/saavu/.env backend/.env

      - name: Stop old containers
        run: docker compose -f docker-compose.staging.yml down

      - name: Start new containers
        run: docker compose -f docker-compose.staging.yml up -d

